version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  api:
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: api
    volumes:
      - ./backend:/backend
    environment:
      RAILS_ENV: development
    ports:
      - "3001:3000"
    depends_on:
      - db
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    command: yarn dev -p 3000
    ports:
      - "3000:3000"
volumes:
  postgresql-data:
    driver: local